// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.wwttr.api;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string service = 1;</code>
   */
  java.lang.String getService();
  /**
   * <code>string service = 1;</code>
   */
  com.google.protobuf.ByteString
      getServiceBytes();

  /**
   * <code>string method = 2;</code>
   */
  java.lang.String getMethod();
  /**
   * <code>string method = 2;</code>
   */
  com.google.protobuf.ByteString
      getMethodBytes();

  /**
   * <code>bytes payload = 3;</code>
   */
  com.google.protobuf.ByteString getPayload();
}
