// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.wwttr.api;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.api.Code code = 1;</code>
   */
  int getCodeValue();
  /**
   * <code>.api.Code code = 1;</code>
   */
  com.wwttr.api.Code getCode();

  /**
   * <code>bytes payload = 2;</code>
   */
  com.google.protobuf.ByteString getPayload();

  /**
   * <code>string message = 3;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string id = 4;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 4;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
