steps:

- name: 'gcr.io/cloud-builders/bazel'
  args:
    - run
    - --define=REVISION_ID=$REVISION_ID
    - --remote_http_cache=https://storage.googleapis.com/wwttr-build-cache
    # - --google_credentials=/path/to/your/secret-key.json
    - --google_default_credentials
    - push

- name: 'supinf/envsubst'
  entrypoint: '/bin/sh'
  args: ['deploy/render.sh']
  env:
  - 'BRANCH_NAME=$BRANCH_NAME'

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'deploy/cluster']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=prod'

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'deploy/app', '--namespace=$BRANCH_NAME']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=prod'
