steps:
# - test: 'gcr.io/cloud-builders/bazel'
#   args: ["build", "main"]
- name: 'gcr.io/cloud-builders/bazel'
  args: ["run", "--define", "REVISION_ID=$REVISION_ID", "push"]
# - name: 'gcr.io/cloud-builders/docker'
#   args: ["push", "gcr.io/ticket-to-ride-216915/ttr:$REVISION_ID"]
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment', '$BRANCH_NAME', 'ttr=gcr.io/ticket-to-ride-216915/ttr:$REVISION_ID']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=prod'
