// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: health.proto

package com.wwttr.health;

public final class Api {
  private Api() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HealthOrBuilder extends
      // @@protoc_insertion_point(interface_extends:health.Health)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.health.Health.Status status = 1;</code>
     */
    int getStatusValue();
    /**
     * <code>.health.Health.Status status = 1;</code>
     */
    com.wwttr.health.Api.Health.Status getStatus();
  }
  /**
   * Protobuf type {@code health.Health}
   */
  public  static final class Health extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:health.Health)
      HealthOrBuilder {
    // Use Health.newBuilder() to construct.
    private Health(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Health() {
      status_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Health(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wwttr.health.Api.internal_static_health_Health_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wwttr.health.Api.internal_static_health_Health_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wwttr.health.Api.Health.class, com.wwttr.health.Api.Health.Builder.class);
    }

    /**
     * Protobuf enum {@code health.Health.Status}
     */
    public enum Status
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNSPECIFIED = 0;</code>
       */
      UNSPECIFIED(0),
      /**
       * <code>READY = 1;</code>
       */
      READY(1),
      /**
       * <code>NOT_READY = 2;</code>
       */
      NOT_READY(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNSPECIFIED = 0;</code>
       */
      public static final int UNSPECIFIED_VALUE = 0;
      /**
       * <code>READY = 1;</code>
       */
      public static final int READY_VALUE = 1;
      /**
       * <code>NOT_READY = 2;</code>
       */
      public static final int NOT_READY_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Status valueOf(int value) {
        return forNumber(value);
      }

      public static Status forNumber(int value) {
        switch (value) {
          case 0: return UNSPECIFIED;
          case 1: return READY;
          case 2: return NOT_READY;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Status>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Status> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Status>() {
              public Status findValueByNumber(int number) {
                return Status.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.wwttr.health.Api.Health.getDescriptor().getEnumTypes().get(0);
      }

      private static final Status[] VALUES = values();

      public static Status valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Status(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:health.Health.Status)
    }

    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <code>.health.Health.Status status = 1;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.health.Health.Status status = 1;</code>
     */
    public com.wwttr.health.Api.Health.Status getStatus() {
      com.wwttr.health.Api.Health.Status result = com.wwttr.health.Api.Health.Status.valueOf(status_);
      return result == null ? com.wwttr.health.Api.Health.Status.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (status_ != com.wwttr.health.Api.Health.Status.UNSPECIFIED.getNumber()) {
        output.writeEnum(1, status_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (status_ != com.wwttr.health.Api.Health.Status.UNSPECIFIED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, status_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wwttr.health.Api.Health)) {
        return super.equals(obj);
      }
      com.wwttr.health.Api.Health other = (com.wwttr.health.Api.Health) obj;

      boolean result = true;
      result = result && status_ == other.status_;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wwttr.health.Api.Health parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wwttr.health.Api.Health parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wwttr.health.Api.Health parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wwttr.health.Api.Health parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wwttr.health.Api.Health parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wwttr.health.Api.Health parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wwttr.health.Api.Health parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wwttr.health.Api.Health parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wwttr.health.Api.Health parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wwttr.health.Api.Health parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wwttr.health.Api.Health parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wwttr.health.Api.Health parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wwttr.health.Api.Health prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code health.Health}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:health.Health)
        com.wwttr.health.Api.HealthOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wwttr.health.Api.internal_static_health_Health_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wwttr.health.Api.internal_static_health_Health_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wwttr.health.Api.Health.class, com.wwttr.health.Api.Health.Builder.class);
      }

      // Construct using com.wwttr.health.Api.Health.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        status_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wwttr.health.Api.internal_static_health_Health_descriptor;
      }

      public com.wwttr.health.Api.Health getDefaultInstanceForType() {
        return com.wwttr.health.Api.Health.getDefaultInstance();
      }

      public com.wwttr.health.Api.Health build() {
        com.wwttr.health.Api.Health result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wwttr.health.Api.Health buildPartial() {
        com.wwttr.health.Api.Health result = new com.wwttr.health.Api.Health(this);
        result.status_ = status_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wwttr.health.Api.Health) {
          return mergeFrom((com.wwttr.health.Api.Health)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wwttr.health.Api.Health other) {
        if (other == com.wwttr.health.Api.Health.getDefaultInstance()) return this;
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wwttr.health.Api.Health parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wwttr.health.Api.Health) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int status_ = 0;
      /**
       * <code>.health.Health.Status status = 1;</code>
       */
      public int getStatusValue() {
        return status_;
      }
      /**
       * <code>.health.Health.Status status = 1;</code>
       */
      public Builder setStatusValue(int value) {
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.health.Health.Status status = 1;</code>
       */
      public com.wwttr.health.Api.Health.Status getStatus() {
        com.wwttr.health.Api.Health.Status result = com.wwttr.health.Api.Health.Status.valueOf(status_);
        return result == null ? com.wwttr.health.Api.Health.Status.UNRECOGNIZED : result;
      }
      /**
       * <code>.health.Health.Status status = 1;</code>
       */
      public Builder setStatus(com.wwttr.health.Api.Health.Status value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.health.Health.Status status = 1;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:health.Health)
    }

    // @@protoc_insertion_point(class_scope:health.Health)
    private static final com.wwttr.health.Api.Health DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wwttr.health.Api.Health();
    }

    public static com.wwttr.health.Api.Health getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Health>
        PARSER = new com.google.protobuf.AbstractParser<Health>() {
      public Health parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Health(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Health> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Health> getParserForType() {
      return PARSER;
    }

    public com.wwttr.health.Api.Health getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetHealthRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:health.GetHealthRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code health.GetHealthRequest}
   */
  public  static final class GetHealthRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:health.GetHealthRequest)
      GetHealthRequestOrBuilder {
    // Use GetHealthRequest.newBuilder() to construct.
    private GetHealthRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetHealthRequest() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetHealthRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wwttr.health.Api.internal_static_health_GetHealthRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wwttr.health.Api.internal_static_health_GetHealthRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wwttr.health.Api.GetHealthRequest.class, com.wwttr.health.Api.GetHealthRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wwttr.health.Api.GetHealthRequest)) {
        return super.equals(obj);
      }
      com.wwttr.health.Api.GetHealthRequest other = (com.wwttr.health.Api.GetHealthRequest) obj;

      boolean result = true;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wwttr.health.Api.GetHealthRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wwttr.health.Api.GetHealthRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wwttr.health.Api.GetHealthRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wwttr.health.Api.GetHealthRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wwttr.health.Api.GetHealthRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wwttr.health.Api.GetHealthRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wwttr.health.Api.GetHealthRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wwttr.health.Api.GetHealthRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wwttr.health.Api.GetHealthRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wwttr.health.Api.GetHealthRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wwttr.health.Api.GetHealthRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wwttr.health.Api.GetHealthRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wwttr.health.Api.GetHealthRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code health.GetHealthRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:health.GetHealthRequest)
        com.wwttr.health.Api.GetHealthRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wwttr.health.Api.internal_static_health_GetHealthRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wwttr.health.Api.internal_static_health_GetHealthRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wwttr.health.Api.GetHealthRequest.class, com.wwttr.health.Api.GetHealthRequest.Builder.class);
      }

      // Construct using com.wwttr.health.Api.GetHealthRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wwttr.health.Api.internal_static_health_GetHealthRequest_descriptor;
      }

      public com.wwttr.health.Api.GetHealthRequest getDefaultInstanceForType() {
        return com.wwttr.health.Api.GetHealthRequest.getDefaultInstance();
      }

      public com.wwttr.health.Api.GetHealthRequest build() {
        com.wwttr.health.Api.GetHealthRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wwttr.health.Api.GetHealthRequest buildPartial() {
        com.wwttr.health.Api.GetHealthRequest result = new com.wwttr.health.Api.GetHealthRequest(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wwttr.health.Api.GetHealthRequest) {
          return mergeFrom((com.wwttr.health.Api.GetHealthRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wwttr.health.Api.GetHealthRequest other) {
        if (other == com.wwttr.health.Api.GetHealthRequest.getDefaultInstance()) return this;
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wwttr.health.Api.GetHealthRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wwttr.health.Api.GetHealthRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:health.GetHealthRequest)
    }

    // @@protoc_insertion_point(class_scope:health.GetHealthRequest)
    private static final com.wwttr.health.Api.GetHealthRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wwttr.health.Api.GetHealthRequest();
    }

    public static com.wwttr.health.Api.GetHealthRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetHealthRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetHealthRequest>() {
      public GetHealthRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetHealthRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetHealthRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetHealthRequest> getParserForType() {
      return PARSER;
    }

    public com.wwttr.health.Api.GetHealthRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  /**
   * Protobuf service {@code health.HealthService}
   */
  public static abstract class HealthService
      implements com.google.protobuf.Service {
    protected HealthService() {}

    public interface Interface {
      /**
       * <code>rpc GetHealth(.health.GetHealthRequest) returns (.health.Health);</code>
       */
      public abstract void getHealth(
          com.google.protobuf.RpcController controller,
          com.wwttr.health.Api.GetHealthRequest request,
          com.google.protobuf.RpcCallback<com.wwttr.health.Api.Health> done);

      /**
       * <code>rpc StreamHealth(.health.GetHealthRequest) returns (stream .health.Health);</code>
       */
      public abstract void streamHealth(
          com.google.protobuf.RpcController controller,
          com.wwttr.health.Api.GetHealthRequest request,
          com.google.protobuf.RpcCallback<com.wwttr.health.Api.Health> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new HealthService() {
        @java.lang.Override
        public  void getHealth(
            com.google.protobuf.RpcController controller,
            com.wwttr.health.Api.GetHealthRequest request,
            com.google.protobuf.RpcCallback<com.wwttr.health.Api.Health> done) {
          impl.getHealth(controller, request, done);
        }

        @java.lang.Override
        public  void streamHealth(
            com.google.protobuf.RpcController controller,
            com.wwttr.health.Api.GetHealthRequest request,
            com.google.protobuf.RpcCallback<com.wwttr.health.Api.Health> done) {
          impl.streamHealth(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.getHealth(controller, (com.wwttr.health.Api.GetHealthRequest)request);
            case 1:
              return impl.streamHealth(controller, (com.wwttr.health.Api.GetHealthRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.wwttr.health.Api.GetHealthRequest.getDefaultInstance();
            case 1:
              return com.wwttr.health.Api.GetHealthRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.wwttr.health.Api.Health.getDefaultInstance();
            case 1:
              return com.wwttr.health.Api.Health.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc GetHealth(.health.GetHealthRequest) returns (.health.Health);</code>
     */
    public abstract void getHealth(
        com.google.protobuf.RpcController controller,
        com.wwttr.health.Api.GetHealthRequest request,
        com.google.protobuf.RpcCallback<com.wwttr.health.Api.Health> done);

    /**
     * <code>rpc StreamHealth(.health.GetHealthRequest) returns (stream .health.Health);</code>
     */
    public abstract void streamHealth(
        com.google.protobuf.RpcController controller,
        com.wwttr.health.Api.GetHealthRequest request,
        com.google.protobuf.RpcCallback<com.wwttr.health.Api.Health> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.wwttr.health.Api.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.getHealth(controller, (com.wwttr.health.Api.GetHealthRequest)request,
            com.google.protobuf.RpcUtil.<com.wwttr.health.Api.Health>specializeCallback(
              done));
          return;
        case 1:
          this.streamHealth(controller, (com.wwttr.health.Api.GetHealthRequest)request,
            com.google.protobuf.RpcUtil.<com.wwttr.health.Api.Health>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.wwttr.health.Api.GetHealthRequest.getDefaultInstance();
        case 1:
          return com.wwttr.health.Api.GetHealthRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.wwttr.health.Api.Health.getDefaultInstance();
        case 1:
          return com.wwttr.health.Api.Health.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends com.wwttr.health.Api.HealthService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void getHealth(
          com.google.protobuf.RpcController controller,
          com.wwttr.health.Api.GetHealthRequest request,
          com.google.protobuf.RpcCallback<com.wwttr.health.Api.Health> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.wwttr.health.Api.Health.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.wwttr.health.Api.Health.class,
            com.wwttr.health.Api.Health.getDefaultInstance()));
      }

      public  void streamHealth(
          com.google.protobuf.RpcController controller,
          com.wwttr.health.Api.GetHealthRequest request,
          com.google.protobuf.RpcCallback<com.wwttr.health.Api.Health> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          com.wwttr.health.Api.Health.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.wwttr.health.Api.Health.class,
            com.wwttr.health.Api.Health.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public com.wwttr.health.Api.Health getHealth(
          com.google.protobuf.RpcController controller,
          com.wwttr.health.Api.GetHealthRequest request)
          throws com.google.protobuf.ServiceException;

      public com.wwttr.health.Api.Health streamHealth(
          com.google.protobuf.RpcController controller,
          com.wwttr.health.Api.GetHealthRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public com.wwttr.health.Api.Health getHealth(
          com.google.protobuf.RpcController controller,
          com.wwttr.health.Api.GetHealthRequest request)
          throws com.google.protobuf.ServiceException {
        return (com.wwttr.health.Api.Health) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.wwttr.health.Api.Health.getDefaultInstance());
      }


      public com.wwttr.health.Api.Health streamHealth(
          com.google.protobuf.RpcController controller,
          com.wwttr.health.Api.GetHealthRequest request)
          throws com.google.protobuf.ServiceException {
        return (com.wwttr.health.Api.Health) channel.callBlockingMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          com.wwttr.health.Api.Health.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:health.HealthService)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_health_Health_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_health_Health_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_health_GetHealthRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_health_GetHealthRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014health.proto\022\006health\"d\n\006Health\022%\n\006stat" +
      "us\030\001 \001(\0162\025.health.Health.Status\"3\n\006Statu" +
      "s\022\017\n\013UNSPECIFIED\020\000\022\t\n\005READY\020\001\022\r\n\tNOT_REA" +
      "DY\020\002\"\022\n\020GetHealthRequest2\202\001\n\rHealthServi" +
      "ce\0225\n\tGetHealth\022\030.health.GetHealthReques" +
      "t\032\016.health.Health\022:\n\014StreamHealth\022\030.heal" +
      "th.GetHealthRequest\032\016.health.Health0\001B\032\n" +
      "\020com.wwttr.healthB\003Api\210\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_health_Health_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_health_Health_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_health_Health_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_health_GetHealthRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_health_GetHealthRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_health_GetHealthRequest_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
